# __init__.py

from .tda import homology_is_trivial, compute_homology_from_facets
from .examples import example_code, example_dictionary

from .code import (
    CombinatorialCode,
    WORD_TYPE,
    boolean_matrix_to_array_of_words,
    sizes_of_words,
    convert_to_boolean_matrix,
    find_maximal_words,
    x_is_a_subset_of_any_in_List,
    NumbaList,
    comb,
    count_bits,
    custom_bit_length,
    intersection_of_codewords_from_bits,
    empty_list,
    bit_order,
    generate_binary_strings,
    array_of_words_to_boolean_matrix,
    array_of_words_to_vectors_of_integers,
    inclusion_relation,
    link_facets,
    x_is_a_superset_of_any_in_List,
    lattice_dictionary_by_size,
    nerve_of_max_words,
    simplicial_violators_from_words,
    Obstructions,
)

__all__ = [
    "CombinatorialCode",
    "WORD_TYPE",
    "boolean_matrix_to_array_of_words",
    "sizes_of_words",
    "convert_to_boolean_matrix",
    "find_maximal_words",
    "x_is_a_subset_of_any_in_List",
    "NumbaList",
    "homology_is_trivial",
    "compute_homology_from_facets",
    "example_code",
    "example_dictionary",
    "comb",
    "count_bits",
    "custom_bit_length",
    "intersection_of_codewords_from_bits",
    "empty_list",
    "bit_order",
    "generate_binary_strings",
    "array_of_words_to_boolean_matrix",
    "array_of_words_to_vectors_of_integers",
    "inclusion_relation",
    "link_facets",
    "x_is_a_superset_of_any_in_List",
    "lattice_dictionary_by_size",
    "nerve_of_max_words",
    "simplicial_violators_from_words",
    "Obstructions",
]
